name: CI

on: push

jobs:
  main:
    name: "Lint and tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install
        run: npm install
      - name: "Lint last commit"
        run: npm run commitlint -- --from ${{ env.sha }}
      - name: "Lint code"
        run: npm run lint --workspaces --if-present
      - name: "Tests"
        run: npm run test --workspaces --if-present
